### ISSUE TITLE
Won't build using Carthage, XCode 7.2.1 [include of non-modular header inside framework module 'ReactiveCocoa']

### ISSUE THREAD

**Issue by andykog** [gitdoapp/RAC-MutableCollectionProperty#11]
I'm not sure, if it is the problem with `RAC-MutableCollectionProperty`, but without it everything works fine.

@pepibumur, do you have any idea why is this happening?

When trying to build project from [cartRACMutableCollection branch](https://github.com/andykog/RACFRC/tree/cartRACMutableCollection):

```
$ carthage update --platform iOS
*** Fetching RAC-MutableCollectionProperty
*** Fetching ReactiveCocoa
*** Fetching Result
*** Downloading Result.framework binary at "1.0.2: A Swift Result"
*** Downloading ReactiveCocoa.framework binary at "v4.0.1"
*** Checking out RAC-MutableCollectionProperty at "3e4de438c0851d9e770326ad6601a7ff00462951"

...

/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:80:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:81:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:82:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:83:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:84:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:85:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
/Users/ak/apps/RACFRC/Carthage/Checkouts/RAC-MutableCollectionProperty/Carthage/Checkouts/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:86:11: error: include of non-modular header inside framework module 'ReactiveCocoa'
<unknown>:0: error: too many errors emitted, stopping now
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
A shell task failed with exit code 65:
2016-03-20 22:16:57.710 xcodebuild[97214:2486118] ### Failed to load Addressbook class CNContactNameFormatter
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

$ xcodebuild -version
Xcode 7.2.1
Build version 7C1002
```

**Comment by pepibumur** [comment]
Have you tried to update the ReactiveCocoa framework version @andykog ?

**Comment by andykog** [comment]
v4.0.1 required by RAC-MutableCollectionProperty is the [latest](https://github.com/ReactiveCocoa/ReactiveCocoa/releases) version available, haven't tried with master

**Comment by andykog** [comment]
Just tried with master in [this repo](https://github.com/andykog/TestRMCP), same error

**Comment by andykog** [comment]
Seems like this is RAC issue ReactiveCocoa/ReactiveCocoa/issues/2557

**Comment by andykog** [comment]
There was the same problem with building framework (`carthage build --no-skip-current`). Seems that adding 'Framework Search Paths' in build settings helped.

**Comment by pepibumur** [comment]
Did you manage to fix it @andykog ?

**Comment by andykog** [comment]
Nope, I just managed to make a build with `carthage build --no-skip-current`.
